# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ConceprFirstRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'

  # Pods for ConceprFirstRxSwift

  target 'ConceprFirstRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConceprFirstRxSwiftUITests' do
    # Pods for testing
  end

end
